My Project: com.capstone.producer.kafka.KafkaProducer Class Reference
com.capstone.producer.kafka.KafkaProducer Class Reference
Static Public Member Functions
static RecordMetadata runProducer (String message, String topicName) throws InterruptedException
static void emitCircularNoFlyZone (CircularNoFlyZone circularNoFlyZone) throws InterruptedException
static void emitPolygonNoFlyZone (PolygonNoFlyZone polygonNoFlyZone) throws InterruptedException
static void emitFlightInformationUpdate (FlightInformation flightInformation) throws InterruptedException
Detailed Description
Class that handles setting up the Kafka production functionality
Member Function Documentation
emitCircularNoFlyZone()
static void com.capstone.producer.kafka.KafkaProducer.emitCircularNoFlyZone (CircularNoFlyZone circularNoFlyZone) throws InterruptedException static
References com.capstone.producer.kafka.KafkaProducer.runProducer(), and com.capstone.producer.shared.JsonHelper.toJson().
emitFlightInformationUpdate()
static void com.capstone.producer.kafka.KafkaProducer.emitFlightInformationUpdate (FlightInformation flightInformation) throws InterruptedException static
References com.capstone.producer.kafka.KafkaProducer.runProducer(), and com.capstone.producer.shared.JsonHelper.toJson().
Referenced by com.capstone.producer.FlightInjectionHandler.handleFlightInjection().
emitPolygonNoFlyZone()
static void com.capstone.producer.kafka.KafkaProducer.emitPolygonNoFlyZone (PolygonNoFlyZone polygonNoFlyZone) throws InterruptedException static
References com.capstone.producer.kafka.KafkaProducer.runProducer(), and com.capstone.producer.shared.JsonHelper.toJson().
runProducer()
static RecordMetadata com.capstone.producer.kafka.KafkaProducer.runProducer (String message, String topicName) throws InterruptedException static
Creates a new Producer Object that is then used to send a ProducerRecord, created from the set Topic name (FlightData) and provided message, through the Kafka broker.
Parameters
message The provided message
Returns
A RecordMetadata Object that relates to the ProducerRecord sent through Kafka in some way
Exceptions
InterruptedException Calling get() on the result of Producer.send(ProducerRecord) can trigger a InterruptedException
Referenced by com.capstone.producer.kafka.KafkaProducer.emitCircularNoFlyZone(), com.capstone.producer.kafka.KafkaProducer.emitFlightInformationUpdate(), com.capstone.producer.kafka.KafkaProducer.emitPolygonNoFlyZone(), com.capstone.producer.ServiceHandler.handleFlightFaId(), com.capstone.producer.ServiceHandler.handleGenerateRequest(), com.capstone.producer.ServiceHandler.updateFlightInfo(), and com.capstone.producer.ServiceHandler.updateGeneratedFlightInfo().
The documentation for this class was generated from the following file:
C:/Users/Bits McGee/Documents/GitHub/FlightTrackerProducer/src/main/java/com/capstone/producer/kafka/KafkaProducer.java