FlightTrackerProducer: com.capstone.producer.clients.AeroApiClientCaller Class Reference
com.capstone.producer.clients.AeroApiClientCaller Class Reference
Public Member Functions
AeroApiClientCaller (RestTemplate client, String baseUrl, String key)
FlightInfoFaid getFlightFromFaId (String flightFaId)
String getFlightFromIdent (String flightIdent)
Operator getOperatorFromId (String operatorId)
List< FlightInfoFaid > getAllActiveFlightsWithLive ()
Detailed Description
Client Caller class that facilitates interaction with the FlightAware's Aero API
Constructor & Destructor Documentation
AeroApiClientCaller()
com.capstone.producer.clients.AeroApiClientCaller.AeroApiClientCaller (RestTemplate client, String baseUrl, String key)
This is the constructor for this client caller class
Parameters
client RestTemplate Object
baseUrl The base aviation stack url used for making the connection
key Aviation Stack API key
Member Function Documentation
getAllActiveFlightsWithLive()
List< FlightInfoFaid > com.capstone.producer.clients.AeroApiClientCaller.getAllActiveFlightsWithLive ()
Gets flight information that correspond to flights that contain live information from the API
Returns
A list of FlightInfo Objects that contain non-null Live Objects
Referenced by com.capstone.producer.ServiceHandler.handleLiveRequest().
getFlightFromFaId()
FlightInfoFaid com.capstone.producer.clients.AeroApiClientCaller.getFlightFromFaId (String flightFaId)
Gets flight information from the API given a flight FaId
Parameters
flightFaId The provided flight aware id number
Returns
A FlightInfo_Id Object that corresponds to the flight with a matching FaId
Referenced by com.capstone.producer.ServiceHandler.handleFlightFaId(), and com.capstone.producer.ServiceHandler.updateFlightInfo().
getFlightFromIdent()
String com.capstone.producer.clients.AeroApiClientCaller.getFlightFromIdent (String flightIdent)
Gets flight information from the API given a flight ident (icao) number
Parameters
flightIdent The ident code (icao) being requested
Returns
A String value corresponding the JSON response from the API
Referenced by com.capstone.producer.ServiceHandler.handleFlightIdent().
getOperatorFromId()
Operator com.capstone.producer.clients.AeroApiClientCaller.getOperatorFromId (String operatorId)
Gets operator (Airline) information from a given operator id
Parameters
operatorId The provided operator id
Returns
An Operator object corresponding to the given id
Referenced by com.capstone.producer.ServiceHandler.handleOperator().
The documentation for this class was generated from the following file:
C:/Users/Bits McGee/Documents/GitHub/FlightTrackerProducer/src/main/java/com/capstone/producer/clients/AeroApiClientCaller.java