FlightTrackerProducer: com.capstone.producer.ServiceHandler Class Reference
com.capstone.producer.ServiceHandler Class Reference
Public Member Functions
ServiceHandler (AviationStackClientCaller aviationStackClientCaller, AeroApiClientCaller aeroApiClientCaller)
String handleFlightIdent (String flightIdent)
String handleFlightFaId (String flightFaId) throws InterruptedException
String handleOperator (String operatorId) throws InterruptedException
String handleLiveRequest ()
String handleGenerateRequest (GenerateRequest generateRequest) throws InterruptedException, HttpException
void handleAirportGenerateRequest (AirportGenerateRequest airportGenerate) throws HttpException
String handleAirportRequest (String airportName)
void updateFlightInfo () throws InterruptedException
void updateGeneratedFlightInfo () throws InterruptedException, HttpException
Detailed Description
Class that facilitates acquiring information from AviationStack, generating mock flights, and 'tracking' live and mock flights
Constructor & Destructor Documentation
ServiceHandler()
com.capstone.producer.ServiceHandler.ServiceHandler (AviationStackClientCaller aviationStackClientCaller, AeroApiClientCaller aeroApiClientCaller)
Constructor for the class. Sets up the Objects used for keeping track of flights
Member Function Documentation
handleAirportGenerateRequest()
void com.capstone.producer.ServiceHandler.handleAirportGenerateRequest (AirportGenerateRequest airportGenerate) throws HttpException
This method handles the generation of mock flights from airport to airport
Parameters
airportGenerate The AirportGenerateRequest Object containing information about the mock flight, including airport names
References com.capstone.producer.clients.AviationStackClientCaller.getAirportInfoFromName().
Referenced by com.capstone.producer.ServiceHandler.handleGenerateRequest().
handleAirportRequest()
String com.capstone.producer.ServiceHandler.handleAirportRequest (String airportName)
Acquires information about the specific airport that corresponds to the provided airport name
Parameters
airportName The provided airport name
Returns
String value that consists of a JSON Object containing the longitude and latitude of the requested airport or an error response.
References com.capstone.producer.clients.AviationStackClientCaller.getAirportInfoFromName().
Referenced by com.capstone.producer.controller.GetInfoController.getAirport().
handleFlightFaId()
String com.capstone.producer.ServiceHandler.handleFlightFaId (String flightFaId) throws InterruptedException
Acquires flight information for the specific flight that corresponds to the provided ICAO number. The information is then parsed and a message is built and sent through Kafka
Parameters
flightFaId The provided flight ICAO number
Returns
The message that was sent to Kafka, which consists of live coordinates and other flight information or an error response.
Exceptions
InterruptedException Sending a message using Kafka can trigger an InterruptedException
References com.capstone.producer.clients.AeroApiClientCaller.getFlightFromFaId(), and com.capstone.producer.kafka.KafkaProducer.runProducer().
Referenced by com.capstone.producer.controller.GetInfoController.getFaId().
handleFlightIdent()
String com.capstone.producer.ServiceHandler.handleFlightIdent (String flightIdent)
Acquires flight information for the specific flight that corresponds to the provided ICAO number. The information is then parsed and a message is built and sent through Kafka
Parameters
flightIdent The provided flight ICAO number
Returns
The message that was sent to Kafka, which consists of live coordinates and other flight information or an error response.
References com.capstone.producer.clients.AeroApiClientCaller.getFlightFromIdent().
Referenced by com.capstone.producer.controller.GetInfoController.getIdent().
handleGenerateRequest()
String com.capstone.producer.ServiceHandler.handleGenerateRequest (GenerateRequest generateRequest) throws InterruptedException, HttpException
Facilitates the creation and tracking of a mock flight with information in the provided request
Parameters
generateRequest Either a GenerateRequest or AirportGenerateRequest Object that contains the necessary information to create a mock flight
Returns
The message that was sent through Kafka, which consists mock live coordinates and other mock flight information or an error response.
Exceptions
InterruptedException Sending a message using Kafka can trigger an InterruptedException
References com.capstone.producer.ServiceHandler.handleAirportGenerateRequest(), and com.capstone.producer.kafka.KafkaProducer.runProducer().
Referenced by com.capstone.producer.controller.GenerateController.generateCustomMockFlight(), and com.capstone.producer.controller.GenerateController.generateMockFlight().
handleLiveRequest()
String com.capstone.producer.ServiceHandler.handleLiveRequest ()
Gets the ICAO numbers of 3-5 flights containing live information. The icaos are then put in a message and sent through Kafka
Returns
String value that consists of a JSON Object containing a comma-separated list of flight icao numbers or an error response.
References com.capstone.producer.clients.AeroApiClientCaller.getAllActiveFlightsWithLive().
Referenced by com.capstone.producer.controller.GetInfoController.getLive().
handleOperator()
String com.capstone.producer.ServiceHandler.handleOperator (String operatorId) throws InterruptedException
Acquires flight information for the specific flight that corresponds to the provided ICAO number. The information is then parsed and a message is built and sent through Kafka
Parameters
operatorId The provided flight ICAO number
Returns
The message that was sent to Kafka, which consists of live coordinates and other flight information or an error response.
Exceptions
InterruptedException Sending a message using Kafka can trigger an InterruptedException
References com.capstone.producer.clients.AeroApiClientCaller.getOperatorFromId().
Referenced by com.capstone.producer.controller.GetInfoController.getOperator().
updateFlightInfo()
void com.capstone.producer.ServiceHandler.updateFlightInfo () throws InterruptedException
Scheduled Method: Runs every 1 minute (60000ms) after an initial delay of 1 minute (60000ms) to account for AviationStack slowness Facilitates the front-end updating of any number of tracked live flights and determines when they should no longer be tracked Iteratively loops through all flight icaos that have been encountered and are still eligible for updating Acquires new flight information from AviationStack and from that builds and sends a new message through Kafka
Exceptions
InterruptedException Sending a message using Kafka can trigger an InterruptedException
References com.capstone.producer.clients.AeroApiClientCaller.getFlightFromFaId(), and com.capstone.producer.kafka.KafkaProducer.runProducer().
updateGeneratedFlightInfo()
void com.capstone.producer.ServiceHandler.updateGeneratedFlightInfo () throws InterruptedException, HttpException
Scheduled Method: Runs every 30 seconds (30000ms) after an initial delay 1 minute (60000ms) to account for the time it takes to put data in the mock flight creation form Facilitates the front-end updating of any number of 'tracked' mock flights and determining when they should no longer be 'tracked' Iteratively loops through all GenerateRequests that have been received and are still eligible for updating Changes flight coordinates based on the provided/calculated rate of change and from that builds and sends a new message through Kafka
Exceptions
InterruptedException Sending a message using Kafka can trigger an InterruptedException
References com.capstone.producer.kafka.KafkaProducer.runProducer().
The documentation for this class was generated from the following file:
C:/Users/Bits McGee/Documents/GitHub/FlightTrackerProducer/src/main/java/com/capstone/producer/ServiceHandler.java