FlightTrackerProducer: com.capstone.producer.shared.JsonHelper Class Reference
com.capstone.producer.shared.JsonHelper Class Reference
Static Public Member Functions
static String toJson (Object obj)
static< T > Optional< T > fromJson (String json, Class< T > clazz)
Detailed Description
JsonHelper class for reading JSON objects
Member Function Documentation
fromJson()
static< T > Optional< T > com.capstone.producer.shared.JsonHelper.fromJson (String json, Class< T > clazz) static
FromJson method for converting the string to an object
Parameters
json Json string to parse
clazz Class used for parsing Json
Returns
String of the JSON
toJson()
static String com.capstone.producer.shared.JsonHelper.toJson (Object obj) static
toJson method for converting the object to a string
Parameters
obj latitude for the object
Returns
String of the JSON
Referenced by com.capstone.producer.kafka.KafkaProducer.emitCircularNoFlyZone(), com.capstone.producer.kafka.KafkaProducer.emitFlightInformationUpdate(), and com.capstone.producer.kafka.KafkaProducer.emitPolygonNoFlyZone().
The documentation for this class was generated from the following file:
C:/Users/Bits McGee/Documents/GitHub/FlightTrackerProducer/src/main/java/com/capstone/producer/shared/JsonHelper.java